using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace greenl8site.Migrations
{
    /// <inheritdoc />
    public partial class FixUserIdIdentityColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Configure the Id column to be an identity column that auto-generates values
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove identity from the Id column
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        }
    }
}
