using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace greenl8site.Migrations
{
    public partial class FixUserIdIdentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Ensure the Id column is an identity column that auto-generates values
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP DEFAULT IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert identity (optional)
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        }
    }
} 