using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace greenl8site.Migrations
{
    public partial class EnsureUsersIdIdentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = current_schema() AND table_name = 'Users'
  ) THEN
    -- If Id is not already an identity column, attempt to make it one
    IF NOT EXISTS (
      SELECT 1
      FROM pg_attribute a
      JOIN pg_class t ON a.attrelid = t.oid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      WHERE n.nspname = current_schema()
        AND t.relname = 'Users'
        AND a.attname = 'Id'
        AND a.attidentity IN ('a','d') -- 'a' = ALWAYS, 'd' = BY DEFAULT
    ) THEN
      BEGIN
        -- Try to add identity (PostgreSQL 10+)
        ALTER TABLE ""Users"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
      EXCEPTION
        WHEN duplicate_object THEN
          -- Already an identity, ignore
          NULL;
        WHEN feature_not_supported THEN
          -- Identity not supported, fall back to sequence default below
          NULL;
      END;

      -- Ensure there is at least a sequence-based default if identity could not be applied
      IF NOT EXISTS (
        SELECT 1
        FROM pg_attrdef d
        JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
        JOIN pg_class t ON t.oid = d.adrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = current_schema()
          AND t.relname = 'Users'
          AND a.attname = 'Id'
          AND d.adsrc LIKE 'nextval%'
      ) THEN
        -- Create a sequence if it does not exist
        IF NOT EXISTS (
          SELECT 1 FROM pg_class s
          JOIN pg_namespace n ON n.oid = s.relnamespace
          WHERE s.relkind = 'S'
            AND n.nspname = current_schema()
            AND s.relname = 'Users_Id_seq'
        ) THEN
          EXECUTE 'CREATE SEQUENCE ""Users_Id_seq""';
        END IF;
        -- Attach the sequence as default
        EXECUTE 'ALTER TABLE ""Users"" ALTER COLUMN ""Id"" SET DEFAULT nextval(''""Users_Id_seq""''::regclass)';
      END IF;
    END IF;
  END IF;
END $$;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Best effort rollback: remove identity and default
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS; ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP DEFAULT;");
        }
    }
} 