using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace greenl8site.Migrations
{
    public partial class FixUserIdIdentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Safely ensure the Id column is an identity column that auto-generates values
            // Only add identity if it doesn't already exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- Check if the column already has identity
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_name = 'Users' 
                        AND column_name = 'Id' 
                        AND is_identity = 'YES'
                    ) THEN
                        -- Drop default if exists and add identity
                        ALTER TABLE ""Users"" ALTER COLUMN ""Id"" DROP DEFAULT IF EXISTS;
                        ALTER TABLE ""Users"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                    END IF;
                END $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert identity (optional)
            migrationBuilder.Sql("ALTER TABLE \"Users\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
        }
    }
} 