using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace greenl8site.Migrations
{
    /// <inheritdoc />
    public partial class AddIdentityToPrimaryKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var tables = new[] { "Categories", "Tags", "Posts", "Pages", "Media" };
            foreach (var table in tables)
            {
                migrationBuilder.Sql($@"
                    ALTER TABLE ""{table}"" 
                    ALTER COLUMN ""Id"" DROP DEFAULT IF EXISTS;
                    ALTER TABLE ""{table}"" 
                    ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                ");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var tables = new[] { "Categories", "Tags", "Posts", "Pages", "Media" };
            foreach (var table in tables)
            {
                migrationBuilder.Sql($@"ALTER TABLE ""{table}"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
